---
server:
  port: 8885
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/shukriev/springcloud-config
          #username:
          #password:
          search-paths:
            - 'station*'